import fs from 'fs';
import { bunnaDistrictsAndAreaOffices } from './src/data/bunnaBranchDirectory';

const manualManagers: Record<string, string> = {
  '101': 'Zelalem (BM)',
  '102': 'Ato Zebene Abera',
  '103': 'Adamu Admasu (BM)',
  '104': 'Ato Ashenafi Tadesse',
  '105': 'Nebiyou Samuel',
  '106': 'Misganaw',
  '107': 'Mengistu Wolelaw',
  '108': 'Asenafi Lakew',
  '109': 'Kifle Mulualem (Acting BM)',
  '110': 'Addisu Abissa (BM)',
  '111': 'Elias Derbie',
  '112': 'Abraha G/silassie Hailu',
  '113': 'Ephrem Meka (BM)',
  '114': 'Eyasu Gebrie',
  '115': 'Biniyam Amado',
  '116': 'Temesgen Mossu Ashagrie',
  '117': 'Yohannes Molla',
  '118': 'Desta Woldesenbet Tiba',
  '119': 'Alem Muluneh Kebret',
  '120': 'Ato Yetemgeta Aregahgn',
  '121': 'Shibire Wakijira',
  '122': 'Ato Million Kiflie',
  '123': 'Dawit Haile Tamerasha',
  '124': 'Girma Workneh',
  '125': 'Ato Gibreyesus Kassaye',
  '126': 'Ato Adinew Hageru',
  '127': 'Chernet Ayalkibet Argaw',
  '128': 'Simegn Gebremichael Dandesa',
  '129': 'Welansa Yakob',
  '130': 'Henok Mengistu (BM)',
  '131': 'Arbisie Derso Zegeye',
  '132': 'Ketema Abera Robi',
  '133': 'Mulatu Shgute Joro',
  '134': 'Wondifraw Melaku',
  '135': 'Bereket',
  '136': 'Abaw Addisu Mitiku',
  '137': 'Asres Menchamo Gichamo',
  '138': 'Temesgen Tesfaye Tenaye',
  '139': 'Mamaru Gizachew Ayalew',
  '140': 'Mebrahtu Hailay G/Mariam',
  '141': 'YIBELTAL HASAB',
  '142': 'Lemesa Abeshu Kitila',
  '143': 'Fikru Hailemariam',
  '144': 'Samrawit Mekonnen',
  '145': 'Mesay Dejene Hailu',
  '146': 'Desalegn Alene (BM)',
  '147': 'Tamirat Tesfaye Terfasa',
  '148': 'Melese Tilahun Ayenew',
  '149': 'Abdi chali Lemi',
  '150': 'Esayas Kidanu Wakwoya',
  '151': 'Ato Dejene Alemu',
  '152': 'Ato Nebiyou Alemu',
  '153': 'Samuel Maru',
  '154': 'Selam Girma',
  '155': 'Getachew Adale Erku',
  '156': 'Molla tuemay',
  '157': 'Yeshi Abadi',
  '158': 'Habtamu',
  '159': 'Tegene Kesisa',
  '160': 'Meseret Manahile',
  '161': 'H/Mariam',
  '162': 'Habtamu Berhanu woldemichael',
  '163': 'Eliyas Lakew',
  '164': 'Dabash Dessie Adane',
  '165': 'Tadese Shumey Bishaw',
  '166': 'Dereje Siyoum (BM)',
  '167': 'Awoke Abebu',
  '168': 'Mesfin Fiker',
  '169': 'Fekadu Tafesse (BM)',
  '170': 'Tewodros',
  '171': 'Yohannes Taddese Gebreyohannes',
  '172': 'Gebreyohannes Woldesenbet (BM)',
  '173': 'Getnet Manaye',
  '174': 'Yasabu Kinde (BM)',
  '175': 'Ato Aboneh W/Mariam',
  '176': 'Ato Ahmed Seid',
  '177': 'Birtukan Atanfu (BM)',
  '178': 'Ato Alene Mognhod',
  '179': 'Dejene Yigezu',
  '180': 'Ato Temesgen Simachew',
  '182': 'Ato Yilkal Damtie',
  '183': 'Ato Getachew Addisie',
  '184': 'Abebech Refera',
  '185': 'Bereket Getachew',
  '186': 'Alemayehu Belachew Shanka',
  '187': 'Abay',
  '188': 'Mamaw Getaneh',
  '189': 'Berihun Ayene Mekonen',
  '190': 'Samrawit Girmay Assefa',
  '191': 'Shishaye Zenebe Tekea',
  '192': 'Alemu',
  '193': 'Gezahegn Endalew',
  '194': 'Yetimgeta',
  '195': 'Ashagrachew',
  '196': 'Shori Hirpasa (BM)',
  '197': 'Sintayehu Tehelku (BM)',
  '198': 'Sefew Tequare',
  '199': 'Melaku Asmare',
  '200': 'Wondowesen Drese (BM)',
  '201': 'Ergoye (acting)',
  '202': 'Mequanent Belay',
  '203': 'Debela Tessema',
  '204': 'Tariku',
  '205': 'W.ro Segen Hailu',
  '206': 'Hagos Hailemariam (BM)',
  '207': 'Tegen Melkamu Chekol',
  '209': 'Desalegn',
  '210': 'Aynshet Amha',
  '212': 'Zerihun Teklemariam',
  '213': 'Lemlem Teferi',
  '214': 'Elias Admasu (BM)',
  '215': 'Almaz Petros (BM)',
  '216': 'Dawait Mengist',
  '217': 'Abayneh Mamo',
  '218': 'Sisay',
  '219': 'Yadeta Beshargo (BM)',
  '220': 'Bereket Abiy',
  '221': 'Melese Shambel Temesgen',
  '222': 'Ato Leyikun Birhanu',
  '223': 'Ato Robel Waga',
  '224': 'Megbaru Ayalu (BM)',
  '225': 'Mikias Sisay',
  '226': 'Tadele Tafese (BM)',
  '227': 'Ato Andinet Hailu',
  '228': 'Wesenu Beyene',
  '229': 'Kassa Gebeyaw Molla',
  '230': 'Yisak Fikadu',
  '231': 'Gobezie Abebe Addisie',
  '232': 'Wakgari Haro Terfasa',
  '233': 'Chala Tola (BM)',
  '234': 'Alehegn Abate Alemu',
  '235': 'Mollu Bishaw (acting)',
  '236': 'Kassahun Amare Weldekidan',
  '237': 'Ato TESFAW GOZGUZ',
  '238': 'Belayab Adane',
  '239': 'Tesfaye Mitiku Feleke (BM)',
  '240': 'Derbew Ayalew Abera',
  '241': 'Zufan Assefa Haile',
  '242': 'Haile Aregay Bahta',
  '243': 'Tesfay Kahsay Gebremedhin',
  '245': 'Armata Godana Roba',
  '246': 'Aklilu Amanuel Tesfaye',
  '247': 'Abebaw Shibru Legesse',
  '248': 'Nega Belay Zeleke',
  '250': 'Abayneh Teshome Estefanos',
  '251': 'Tewodros Dagnachew (BM)',
  '252': 'Ato Yoseph Tadesse',
  '253': 'Belayneh Mekomnen Sinishaw',
  '254': 'Liminih Girma Mekonen',
  '255': 'Sentayehu G/Wold',
  '256': 'Muleta Jamma (BM)',
  '257': 'Ato Tsegaye Atsibha',
  '258': 'Bekele Assefa Amdineh',
  '259': 'Ato Kefelegn W/Yohannis',
  '260': 'Mekuriyaw Tadese Yitayew',
  '261': 'Teketel Elias Wontebo',
  '262': 'Alazar Gebrekidan',
  '263': 'Negussie Demilew (BM)',
  '264': 'Woretaw Sisay',
  '265': 'Sisay Feyisa (BM)',
  '266': 'Engidashet Kebede',
  '268': 'Ato zarihun Tamiru',
  '269': 'Ashenafi Abatkun Debero',
  '270': 'Lijalem Workneh (BM)',
  '271': 'Ousman Ahmed Mohammed',
  '272': 'Samuel Mintesnot',
  '273': 'Aynaku Sifir',
  '274': 'Rega Tesfaye',
  '275': 'Temesgen Estibel (BM)',
  '276': 'Hailemariam Tefera',
  '277': 'Tsion Legese',
  '278': 'Boja Dereje',
  '279': 'Biritu Gonfa',
  '280': 'Ato Habib Eliyas',
  '281': 'Ato Maedot Teshome',
  '282': 'Fekadu',
  '283': 'Zinabu Kifle',
  '284': 'Genet Gebremeskel Alemayehu',
  '286': 'Demeke Tilahun',
  '288': 'W.ro Hemen Mekuria',
  '289': 'Zelalem Habtamu',
  '290': 'Solomon Atsbeha (BM)',
  '291': 'Solomon Kiflemichale (BM)',
  '292': 'Adisu Desalegn (BM)',
  '293': 'Ato Tilahun Eshetu',
  '295': 'Habetamu Banga',
  '296': 'Senait Bekele',
  '297': 'Yalemwork Birhane',
  '298': 'Melese',
  '299': 'Tsegaslassie Gebregergs Kahsay',
  '302': 'Deme Biranu (BM)',
  '303': 'Henok Solomon (BM)',
  '304': 'Simachew Shiferaw Desta',
  '305': 'Lamesgine Minyichil',
  '306': 'Betelihem',
  '307': 'Selamawit Wolde',
  '308': 'Wasshun Mamushet (BM)',
  '309': 'Tesfaye Tirfie',
  '311': 'Gebrie Belay',
  '312': 'Solomon Biru',
  '314': 'Atirsaw Tewachew',
  '315': 'Yihunie Ebstu Deyibelew',
  '316': 'Ejigu',
  '317': 'Teketay Alemnew',
  '318': 'Bewket Kerie',
  '319': 'Abubeker Minwuye',
  '320': 'Erziku Desalegn (BM)',
  '321': 'Workayehu Situneh',
  '322': 'Birhanu',
  '323': 'Tewachew Gebeyaw',
  '324': 'Mihretabe',
  '325': 'Tsegaye Nibret',
  '327': 'Selamawit Geremew',
  '328': 'Fisseha Dagnaw Melese',
  '329': 'Derso Mengesha Dinku',
  '330': 'Kidanemariam',
  '331': 'G/hiwot Mulu',
  '332': 'Emebet Leku',
  '333': 'Weldemaryam Giday Weldetnsae',
  '334': 'Tazabi Dagne',
  '335': 'Dagne Merga',
  '336': 'Tirunesh Getnet',
  '338': 'Ato Abebe Shifera',
  '339': 'Berhanu Hailekiros Gebru',
  '340': 'Wondosen Abebe',
  '341': 'Addisu Kerebih Mekonen',
  '342': 'Setargew Mengist',
  '344': 'Biruk',
  '345': 'Getaneh Shiferaw',
  '346': 'Zinaw Bilhatie Damtie',
  '347': 'Abrehan zemedikun',
  '348': 'Belay Erko (BM)',
  '349': 'Tesfamichael Abebaw (BM)',
  '350': 'Zemenu Tadesse Guangul',
  '351': 'Yitbarek Tamene',
  '352': 'Ato Demsash Moges',
  '353': 'Ato Legese Yayehyirad',
  '354': 'Agunew Birhanu (BM)',
  '355': 'Ato Getu Damitew',
  '356': 'Meskerem Birhanu',
  '357': 'Ato Gizachew Muluneh',
  '358': 'Mebrat Agasue',
  '360': 'Negash',
  '361': 'bizuneh',
  '362': 'Ato yismashewa',
  '363': 'Amsale Zewdu',
  '364': 'Nardos Getahun',
  '365': 'Yetagesu',
  '366': 'Matiwos Dufera (BM)',
  '367': 'Ato Mewail Yared',
  '368': 'Aklilu Ermias Hibebo',
  '369': 'Getachew',
  '370': 'Abinet tamru',
  '371': 'Ato Aschalew Derbe',
  '372': 'Wondimu Mere Gatamtate',
  '373': 'Tamene Tadesse Kute',
  '374': 'Jemal Mohammed (BM)',
  '375': 'Birhanu Animaw Admasie',
  '376': 'Esubalew Mengistie',
  '377': 'Tagay Wolde Gebermariam',
  '378': 'Habtamu Tiruneh Debela',
  '379': 'Ato Metadel Fenta',
  '380': 'Minuyelet Mulu Gebeyehu',
  '381': 'Asmare Tamiru',
  '382': 'Mekbib Meshageria Abera',
  '383': 'Ato Biruk Hailu (Acting)',
  '384': 'Ato Fetsum Tadesse',
  '385': 'Kedir Alemu',
  '386': 'Nehemia Tilahun (BM)',
  '387': 'Addisu Tekewa',
  '388': 'Kumilign Shiferaw',
  '389': 'Ato Yohans Gizaw',
  '390': 'Ato Alemu Wubie',
  '391': 'Ato wubshet Belete',
  '392': 'Dagim Zewdie',
  '393': 'Mustefa',
  '394': 'Nathaniel Desalgne (BM)',
  '395': 'Eskeziaw Demelash',
  '396': 'Belayneh',
  '397': 'Bezunesh Berhanu',
  '398': 'Abebaw Niguse',
  '399': 'Dagachew',
  '400': 'Chaltu Ashe',
  '401': 'Mekashaw Abate',
  '402': 'Surafel Mekonen',
  '403': 'Seid Assen Endrie',
  '404': 'Gizew Endazeze',
  '405': 'Etalem Fikre Sebesibe (BM)',
  '406': 'Almaz Tesema',
  '407': 'Aragaw Ayalew Baylie',
  '408': 'Temesgen Tadele Hunegnaw',
  '409': 'Gebru Nigatu',
  '410': 'Getnet Haimanot Atinaf',
  '411': 'Ato Yoseph Alaye',
  '413': 'Abnet Kidmealem Amare',
  '414': 'Anwar Abdella',
  '415': 'Addisu Mossie Mihretu',
  '416': 'Ato Yared Fikadu (Acting)',
  '418': 'Menelik Getachew Kasaye',
  '419': 'Yohannes Limeneh',
  '420': 'Adane Tadele Abebe',
  '421': 'Yargal Molla',
  '422': 'Mekuriyaw Wale Kirkos',
  '423': 'Segni Gelgelu',
  '424': 'Getahun Genene',
  '425': 'Amsalu Debas',
  '426': 'Abebe Tefera',
  '427': 'Lemi Shuferi',
  '428': 'Ato Cherugeta Ayele',
  '429': 'Bizuneh Hailu',
  '430': 'Bekele Mengesha',
  '431': 'Minayehu Workneh',
  '432': 'Muluneh Debele (BM)',
  '433': 'Desalegn Olani Biru',
  '434': 'ato Haile Negash',
  '435': 'Melkamu Bekele Betela',
  '436': 'Zelalem Teshay Alemayehu',
  '437': 'Tegegne Mengstie Beshir',
  '438': 'Meaza Alemayehu',
  '439': 'Abrham',
  '440': 'Tilahun Bihon Legesse',
  '441': 'Abera Belay Kassaw',
  '442': 'Endalekachew Teferra Ewunu',
  '443': 'Abebe Molla Desale',
  '444': 'Belay Gebrie (Acting BM)',
  '445': 'Biruk Mersha (BM)',
  '446': 'KINETIBEB MENGISTU',
  '447': 'Ato Belayhun Walelu',
  '448': 'Atitegeb Eshetu',
  '449': 'Hiwot Daniel',
  '450': 'Zerihun Tamiru',
  '452': 'Ato Amanuel Tamene (Acting)',
  '453': 'Temesgen Emiru Belay',
  '454': 'Yonas Kassa',
  '455': 'Aiemro Awoke',
  '456': 'Masresha Abebe',
  '457': 'Fantahun Seyoum (BM)',
  '458': 'Demwoze Henok Mekonen',
  '459': 'Tsegahun Alemu Dagne',
  '460': 'Melaku Tilahun',
  '461': 'Temesgen Birega Biru',
  '462': 'Tenaw Belete',
  '464': 'Ato Tibebe Alemu',
  '465': 'Kumlgn Shiferaw',
  '466': 'Seid Mohammed Adem',
  '467': 'belsti Atnafu',
  '468': 'Henoke Gebremariam Yirga',
  '469': 'Ermias',
  '470': 'Genetu Admas',
  '471': 'Merid Bote Boshe',
  '473': 'Asnake Enawgaw Biyabile',
  '474': 'Tariku Ayele Lakew',
  '475': 'Ato Getaw Agonafr',
  '476': 'Getachew Dessie (acting)',
  '477': 'Tajebe (acting)',
  '478': 'Befikadu Belete',
  '479': 'Wubalem Tsegaye',
  '480': 'Temesgen Derbew Dejen',
  '481': 'Solomon Mengstie Asefa',
  '482': 'Yeshiwas Getahun Belete',
  '483': 'Bedasa Habte Mokonen',
  '484': 'Gugisa Eshete (BM)',
  '485': 'Askal Zekariyas',
  '486': 'Mustefa Abduljewad',
  '487': 'Fentahun Muche',
  '488': 'Mesfin Shiferaw',
  '489': 'Nebiyou Assefa',
  '490': 'Biyaregew Sihn',
  '491': 'Nebiyu',
  '492': 'Desta Demllew Kassa',
  '493': 'Meseret Yonas Mota',
  '494': 'Feyisa Kitila Gutu',
  '495': 'Kindualem Haile Haybano',
  '496': 'Mengesha Alemu Ettiso',
  '497': 'Getachew Abache Fitamo',
  '498': 'Ato Haile Negash',
  '499': 'Habtamu',
  '501': 'Bamlaku Atalay Alemayehu',
  '503': 'Lidet Nigussie',
  '504': 'Zerihun',
  '505': 'Abera Chanie Shibesh',
  '506': 'Geletaw Beyene Getie',
  '507': 'Abdu Assefa Belay',
  '508': 'Desta Belay Derbew',
  '509': 'Andualem (acting)',
  '510': 'Bantigegn Asires',
  '511': 'Mazengiya Nigatu',
  '512': 'Girma Belete',
  '513': 'Ato Demsew Shewanyazew',
  '514': 'Chekole Yideg (acting)',
  '515': 'Gosa Asefa',
  '516': 'Dawit Tadesse',
  '517': 'Mahlet Birhanu',
  '518': 'Gion Belayneh',
  '519': 'Abebaw',
  '520': 'Dagnachew Amene',
  '521': 'Wube Fetene',
  '522': 'Ayantu Bekele (BM)',
  '523': 'Yinebeb Ayalew',
  '524': 'Ato Demsew Shewanyazew',
  '525': 'Ato Tazabi Dejen',
  '526': 'Beshewa Damtew',
  '527': 'Matusal Petros Bacho',
  '528': 'Mengistu Abebe (BM)',
  '529': 'Mestawet Niguse',
  '534': 'Wegene Dola Dogiso',
  '535': 'Gizat Abita',
  '536': 'Aberra Teshome (acting)',
  '537': 'ATO YOHANNES AZIZ',
  '538': 'Merga Argeta Geleta',
  '539': 'Mamush',
  '540': 'Zeru Dessalgn Yimer',
  '541': 'Biruk Leikun Menegesha',
  '542': 'Addisalem Sintayehu',
  '543': 'Dejen Bisetegn Sitot',
  '544': 'Tilaye Yeshanbel Beza',
  '545': 'Lishan Getiye',
  '546': 'Tekil Worku',
  '547': 'Degu Deribie Wondie',
  '548': 'Aragaw',
  '549': 'Ayalew Tegegn',
  '550': 'Dessale Dejen Tizazu',
  '551': 'Mohammed Yimam Siraj',
  '552': 'Geleta Rahmeto',
  '553': 'Yibeltal Yalew Assaye',
  '554': 'Yimer Baynes Abegaz',
  '555': 'Asaminew Gebrie',
  '556': 'Ato Workneh Tola',
  '557': 'Fikadu Abebe (BM)',
  '558': 'Hayat Hussien Mohammed',
  '559': 'Nuru Hussen',
  '560': 'Habtamu Tafese',
  '561': 'Simon Chekol Asefa',
  '562': 'Setamlak Gedefaw Shiferaw',
  '563': 'Andualem Yitibarek',
  '564': 'Beyene Bafa Biliso',
  '565': 'Desta Kelbamo Abiyo',
  '566': 'Ato Temesgen Yeshidnber',
  '567': 'Wendesen Feleke (BM)',
  '569': 'Moges Birara Temere',
  '570': 'Ashebir Abayneh',
  '571': 'Zinash Major',
  '572': 'Yetnayet Teshome',
  '573': 'Bacha Teshome',
  '574': 'Getachew Worku',
  '575': 'Aklilu Getachew',
  '576': 'Meressa Mereba',
  '577': 'Godie Balew Alemu',
  '578': 'Admasu Atrise Adeto',
  '579': 'Samuel Alemayehu'
};

function updateFile(filePath: string) {
  if (!fs.existsSync(filePath)) return;
  const content = fs.readFileSync(filePath, 'utf-8');
  let data: any;
  if (filePath.endsWith('.ts')) {
    const match = content.match(/export const bunnaBranchDirectory: Branch\[\s*\] = (\[[\s\S]*\]);/);
    if (!match) return;
    data = eval(match[1]);
  } else {
    data = JSON.parse(content);
  }

  let updated = 0;
  const arr = Array.isArray(data) ? data : data.branches;
  if (arr) {
    for (const b of arr) {
      const sol = String(b.solId || b.code || '');
      if (manualManagers[sol]) {
        b.managerName = manualManagers[sol];
        updated++;
      }
    }
  }

  if (filePath.endsWith('.ts')) {
    const newContent = `import { District, Branch } from '../types';\n\nexport const bunnaDistrictsAndAreaOffices: District[] = ${JSON.stringify(bunnaDistrictsAndAreaOffices, null, 2)};\n\nexport const bunnaBranchDirectory: Branch[] = ${JSON.stringify(data, null, 2)};\n`;
    fs.writeFileSync(filePath, newContent, 'utf-8');
  } else {
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
  }
  console.log(`Updated ${updated} managers in ${filePath}`);
}

updateFile('./src/data/bunnaBranchDirectory.ts');
updateFile('./official_branches.json');
updateFile('./epms_persistent_data.json');
